### ISSUE TITLE
RuntimeError: Internal C++ object (PySide6.QtWidgets.QTableWidgetItem) already deleted.

### ISSUE THREAD

**Issue by LorenEteval** [LorenEteval/Furious#14]
```
[2023-09-12 17:25:48,303] [Furious.Gui.Action] [INFO] action is 'Save'. Checked is False
[2023-09-12 17:25:50,722] [Furious.Utility.Process] [ERROR] stopped with exitcode 1
Traceback (most recent call last):
  File "EditConfiguration.py", line 1576, in handleItemSelectionChanged
    self.doNotSwitchCallback()
  File "EditConfiguration.py", line 1536, in doNotSwitchCallback
    self.setCurrentIndex(self.indexFromItem(prevItem))
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Internal C++ object (PySide6.QtWidgets.QTableWidgetItem) already deleted.
```

**Comment by LorenEteval** [comment]
Possible fix: 3930565b03207c8237ac2117a63ffa196402ccc9
