### ISSUE TITLE
pip install failed on Linux platform

### ISSUE THREAD

**Issue by tianrking** [LorenEteval/Furious#27]
```
 writing manifest file 'hysteria.egg-info/SOURCES.txt'
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      installing to build/bdist.linux-x86_64/wheel
      running install
      # github.com/quic-go/quic-go/internal/qtls
      /home/w0x7ce/go/pkg/mod/github.com/apernet/quic-go@v0.34.1-0.20230507231629-ec008b7e8473/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/setup.py", line 84, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 335, in run
          self.run_command('install')
        File "/usr/lib/python3.10/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/setup.py", line 74, in run
          buildHysteria()
        File "/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/setup.py", line 29, in buildHysteria
          runCommand(
        File "/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/setup.py", line 23, in runCommand
          subprocess.run(command, check=True)
        File "/usr/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['go', 'build', '-C', 'hysteria-go', '-o', '/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/gobuild/hysteria.a', '-buildmode=c-archive', '-trimpath', '-ldflags', '-s -w -buildid=', './app/cmd']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for hysteria
  Running setup.py clean for hysteria
Failed to build hysteria
Installing collected packages: hysteria, ujson, pybase64, ping3, darkdetect, Furious-GUI
  Running setup.py install for hysteria ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for hysteria did not run successfully.
  │ exit code: 1
  ╰─> [27 lines of output]
      running install
      /usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      # github.com/quic-go/quic-go/internal/qtls
      /home/w0x7ce/go/pkg/mod/github.com/apernet/quic-go@v0.34.1-0.20230507231629-ec008b7e8473/internal/qtls/go121.go:5:13: cannot use "The version of quic-go you're using can't be built on Go 1.21 yet. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built on Go 1.21 yet. F...) as int value in variable declaration
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/setup.py", line 84, in <module>
          setup(
        File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.10/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.10/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.10/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/setup.py", line 74, in run
          buildHysteria()
        File "/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/setup.py", line 29, in buildHysteria
          runCommand(
        File "/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/setup.py", line 23, in runCommand
          subprocess.run(command, check=True)
        File "/usr/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['go', 'build', '-C', 'hysteria-go', '-o', '/tmp/pip-install-86_xoa50/hysteria_1f969bf0e0994182a31981c105395dff/gobuild/hysteria.a', '-buildmode=c-archive', '-trimpath', '-ldflags', '-s -w -buildid=', './app/cmd']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> hysteria

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

```

**Comment by StarChenPy** [comment]
Please use version 1.20. x of go

**Comment by LorenEteval** [comment]
Indeed. I just seperated hysteria cores as extra dependencies to avoid build problems 6ef279d9648f8c0ba113db4c07666e81ad4b7eb3.

Since you are using `go 1.21`, please retry with `pip install "Furious-GUI[go1.21]"`. Notice that it will not install legacy hy1 core.

**Comment by tianrking** [comment]
thx bro,  however still fail that building with go1.21.3 linux/amd64

**Comment by LorenEteval** [comment]
> thx bro, however still fail that building with go1.21.3 linux/amd64

Need error logs.
