### ISSUE TITLE
ImportError: libicudata.so.73: ELF load command address/offset not page-aligned

### ISSUE THREAD

**Issue by txl263** [LorenEteval/Furious#49]
OS: Arch Linux x86_64
Kernel: 6.5.7-arch1-1

Traceback (most recent call last):
  File "/opt/furious/__main__.py", line 18, in <module>
  File "/opt/furious/Furious/__init__.py", line 18, in <module Furious>
  File "/opt/furious/Furious/Utility/Resources.py", line 6, in <module Furious.Utility.Resources>
ImportError: libicudata.so.73: ELF load command address/offset not page-aligned

**Comment by LorenEteval** [comment]
This seems not related to the application itself. You might want to refer to the package publisher for help.
