### ISSUE TITLE
Installation Arch-base linux

### ISSUE THREAD

**Issue by mmtech2012** [LorenEteval/Furious#67]
my OS is endeavouros which is Arch-base linux
trying to install this package using this command
`pipx install Furious-GUI`
but installation failed.
I leave a log for inspect.
[cmd_2024-02-10_13.34.50_pip_errors.log](https://github.com/LorenEteval/Furious/files/14228846/cmd_2024-02-10_13.34.50_pip_errors.log)

**Comment by LorenEteval** [comment]
I cannot help with the logs since I'm not an archlinux user. I'll leave your logs here for anyone who encounters the same.

```
PIP STDOUT
----------
Collecting furious-gui
  Using cached Furious_GUI-0.3.0-py3-none-any.whl.metadata (2.6 kB)
Collecting PySide6 (from furious-gui)
  Using cached PySide6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (5.3 kB)
Collecting tun2socks>2.5.1 (from furious-gui)
  Using cached tun2socks-2.5.2.tar.gz (588 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting ujson (from furious-gui)
  Using cached ujson-5.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.7 kB)
Collecting pybase64 (from furious-gui)
  Using cached pybase64-1.3.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (7.9 kB)
Collecting pyqrcode (from furious-gui)
  Using cached PyQRCode-1.2.1-py3-none-any.whl
Collecting pypng (from furious-gui)
  Using cached pypng-0.20220715.0-py3-none-any.whl (58 kB)
Collecting ping3 (from furious-gui)
  Using cached ping3-4.0.4-py3-none-any.whl (13 kB)
Collecting darkdetect (from furious-gui)
  Using cached darkdetect-0.8.0-py3-none-any.whl (9.0 kB)
Collecting shiboken6==6.6.1 (from PySide6->furious-gui)
  Using cached shiboken6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (2.5 kB)
Collecting PySide6-Essentials==6.6.1 (from PySide6->furious-gui)
  Using cached PySide6_Essentials-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (3.7 kB)
Collecting PySide6-Addons==6.6.1 (from PySide6->furious-gui)
  Using cached PySide6_Addons-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl.metadata (3.9 kB)
Using cached Furious_GUI-0.3.0-py3-none-any.whl (9.3 MB)
Using cached pybase64-1.3.2-cp311-cp311-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (68 kB)
Using cached PySide6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (77 kB)
Using cached PySide6_Addons-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (125.2 MB)
Using cached PySide6_Essentials-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (82.3 MB)
Using cached shiboken6-6.6.1-cp38-abi3-manylinux_2_28_x86_64.whl (245 kB)
Using cached ujson-5.9.0-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (53 kB)
Building wheels for collected packages: tun2socks
  Building wheel for tun2socks (setup.py): started
  Building wheel for tun2socks (setup.py): finished with status 'error'
  Running setup.py clean for tun2socks
Failed to build tun2socks

PIP STDERR
----------
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [77 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib
      creating build/lib/tun2socks
      copying tun2socks/__init__.py -> build/lib/tun2socks
      running egg_info
      writing tun2socks.egg-info/PKG-INFO
      writing dependency_links to tun2socks.egg-info/dependency_links.txt
      writing top-level names to tun2socks.egg-info/top_level.txt
      reading manifest file 'tun2socks.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching 'tun2socks.*' under directory 'tun2socks'
      adding license file 'LICENSE'
      writing manifest file 'tun2socks.egg-info/SOURCES.txt'
      /home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      installing to build/bdist.linux-x86_64/wheel
      running install
      # gvisor.dev/gvisor/pkg/sync
      /home/mmtech/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230603040744-5c9219dedd33/pkg/sync/gate_unsafe.go:114:3: undefined: goready
      /home/mmtech/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230603040744-5c9219dedd33/pkg/sync/gate_unsafe.go:144:2: undefined: gopark
      /home/mmtech/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230603040744-5c9219dedd33/pkg/sync/rwmutex_unsafe.go:76:3: undefined: semacquire
      /home/mmtech/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230603040744-5c9219dedd33/pkg/sync/rwmutex_unsafe.go:102:4: undefined: semrelease
      /home/mmtech/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230603040744-5c9219dedd33/pkg/sync/rwmutex_unsafe.go:152:3: undefined: semacquire
      /home/mmtech/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230603040744-5c9219dedd33/pkg/sync/rwmutex_unsafe.go:179:3: undefined: semrelease
      /home/mmtech/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230603040744-5c9219dedd33/pkg/sync/rwmutex_unsafe.go:207:3: undefined: semrelease
      /home/mmtech/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230603040744-5c9219dedd33/pkg/sync/seqcount.go:87:6: undefined: canSpin
      /home/mmtech/go/pkg/mod/gvisor.dev/gvisor@v0.0.0-20230603040744-5c9219dedd33/pkg/sync/seqcount.go:89:4: undefined: doSpin
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4uhzvrxi/tun2socks_3494d1cd8a924d11a34e2c32583fb0af/setup.py", line 77, in <module>
          setup(
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/wheel/bdist_wheel.py", line 404, in run
          self.run_command("install")
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/dist.py", line 989, in run_command
          super().run_command(command)
        File "/home/mmtech/.local/pipx/shared/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-4uhzvrxi/tun2socks_3494d1cd8a924d11a34e2c32583fb0af/setup.py", line 67, in run
          buildTun2socks()
        File "/tmp/pip-install-4uhzvrxi/tun2socks_3494d1cd8a924d11a34e2c32583fb0af/setup.py", line 23, in buildTun2socks
          runCommand(
        File "/tmp/pip-install-4uhzvrxi/tun2socks_3494d1cd8a924d11a34e2c32583fb0af/setup.py", line 17, in runCommand
          subprocess.run(command, check=True)
        File "/usr/lib/python3.11/subprocess.py", line 571, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['go', 'build', '-C', 'tun2socks-go', '-o', '/tmp/pip-install-4uhzvrxi/tun2socks_3494d1cd8a924d11a34e2c32583fb0af/gobuild/tun2socks.a', '-buildmode=c-archive', '-trimpath', '-ldflags', '-s -w -buildid=']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tun2socks
ERROR: Could not build wheels for tun2socks, which is required to install pyproject.toml-based projects

```
